/* Automatically generated by configure */
#ifndef COMPONENTS_CONFIG_H
#define COMPONENTS_CONFIG_H


int _papi_hwi_max_presets[] = {
   PAPI_MAX_PRESET_EVENTS,
   0,
   0,
   0
};

hwi_presets_t *_papi_hwi_comp_presets[] = {
   _papi_hwi_presets,
   NULL,
   NULL,
   NULL
};

extern papi_vector_t _perf_event_vector;
extern papi_vector_t _perf_event_uncore_vector;
extern papi_vector_t _sysdetect_vector;

struct papi_vectors *_papi_hwd[] = {
   &_perf_event_vector,
   &_perf_event_uncore_vector,
   &_sysdetect_vector,
   NULL
};

#endif
